### PR TITLE
Add SQL script for creating flights, passengers, bookings tables and …

### PR DESCRIPTION
**Pull request by legend-crypt**
…related functions and views

### CODE REVIEW

**Comment by legend-crypt** [comment]
Add SQL script for creating flights, passengers, bookings tables and … #2

**Review by Cobby-a — APPROVED** [review]

**Review by michaelkedey — APPROVED** [review]
awesome

**Review by Tracy350 — APPROVED** [review]

**Review by LizzyDzifa — APPROVED** [review]

**Review by Rogers030 — APPROVED** [review]
Awesome

**Review by Kar-Ta — APPROVED** [review]

**Review by Tracy350 — COMMENTED** [review]
awesome

**Pull request merged**
